#include <stdio.h>
void main()
{
    char nombre[20], apellido[20], lugar[30], mes [10], color [20], hobbie [50], deporte[20], animal [20], pelicula [30], libro [30], juego[20], heroe [20], artista [20], genero [20], valorar [50], gustser [30], defecto [20], personaje [30], frase [50];
    int edad, dia, year;
    printf("Escriba su nombre: ");
    scanf("%s",nombre);
    printf("Escriba su apellido: ");
    scanf("%s",apellido);
    printf("Escriba su edad: ");
    scanf("%i",&edad);
    printf("Escriba el dia de su nacimiento: ");
    scanf("%i",&dia);
    printf("Escriba el mes de su nacimiento: ");
    scanf("%s",mes);
    printf("Escriba el año de su nacimiento: ");
    scanf("%i",&year);
    printf("Escriba su color favorito: ");
    scanf("%s",color);
    printf("Escriba su o sus hobbies: ");
    scanf("%s",hobbie);
    printf("Escriba su deporte favorito:  ");
    scanf("%s",deporte);
    printf("Escriba su animal favorito: ");
    scanf("%s",animal);
    printf("Escriba su pelicula favorita: ");
    scanf("%s",pelicula);
    printf("Escriba su libro favorito: ");
    scanf("%s",libro);
    printf("Escriba su juego favorito: ");
    scanf("%s",juego);
    printf("Escriba su super heroe favorito: ");
    scanf("%s",heroe);
    printf("Escriba su artista musical favorito: ");
    scanf("%s",artista);
    printf("Escriba su genero musical favorito: ");
    scanf("%s",genero);
    printf("Escriba lo que mas valora en una persona: ");
    scanf("%s",valorar);
    printf("Escriba como le gusta ser con las personas: ");
    scanf("%s",gustser);
    printf("Escriba su mayor defecto: ");
    scanf("%s",defecto);
    printf("Escriba su personaje historico favorito: ");
    scanf("%s",personaje);
    printf("Escriba su frase favorita: ");
    scanf("%s",frase);
    printf("\n");
    printf("-----------------\n");
    printf("\n");
    printf("Biografia \n");
    printf("\n");
    printf("-----------------\n");
    printf("\n");
    printf("Mi nombre es: %s \n", nombre);
    printf("Mi apellido es: %s \n",apellido);
    printf("Mi edad es: %i años \n",edad);
    printf("Naci el: %i de %s de %i \n",dia, mes, year);
    printf("Mi color favorito es el: %s \n",color);
    printf("Mi hobbie favorito es: %s \n", hobbie);
    printf("Mi deporte favorito es: %s \n", deporte);
    printf("Mi animal favorito es el: %s \n", animal);
    printf("Mi pelicula favorita es: %s \n", pelicula);
    printf("Mi libro favorito es: %s \n", libro);
    printf("Mi juego favorito es: %s \n", juego);
    printf("Mi super heroe favorito es: %s \n", heroe);
    printf("Mi artista musical favorito es: %s \n", artista);
    printf("Mi genero musical favorito es: %s \n", genero);
    printf("Lo que mas valoro en una persona es: %s \n", valorar);
    printf("Me gusta ser %s con las personas. \n", gustser);
    printf("Mi mayor defecto es: %s \n", defecto);
    printf("Mi personaje histórico favorito es: %s \n", personaje);
    printf("Mi frase favorita es: %s \n", frase);
}
